name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - test-action-hugging-space

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with Hugging Face
      uses: ramonvc/huggingface-sync-action@v0.0.1
      with:
        github_repo_id: ramonvc/freegpt-webui
        huggingface_repo_id: monra/test
        repo_type: space
        space_sdk: docker
        app_port: 1338
        hf_token: ${{ secrets.HF_TOKEN }}
